version: '2.2'

services:
  claude_shop_db:
    extends:
      file: common.yml
      service: claude_shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariapwd

  claude_shop_php-fpm:
    extends:
      file: common.yml
      service: claude_shop_php-fpm
    depends_on:
      - claude_shop_redis
    restart: always
    build:
      args:
        development: 1
        http_proxy: http://10.0.3.15:3128
        https_proxy: http://10.0.3.15:3128
        phpini: php_dev_claude.ini
    environment:
      XDEBUG_CONFIG: "client_host=10.0.3.15"
      PHP_IDE_CONFIG: serverName=portal
      http_proxy: http://10.0.3.15:3128
      https_proxy: http://10.0.3.15:3128
    links:
      - claude_shop_db

  claude_shop_nginx:
    extends:
      file: common.yml
      service: claude_shop_nginx
    restart: always
    depends_on:
      - claude_shop_php-fpm
    build:
      args:
        development: 1
        nginxconf: nginx_dev_claude.conf
        http_proxy: http://10.0.3.15:3128
        https_proxy: http://10.0.3.15:3128
    labels:
      - "traefik.http.routers.portal2018-secure.rule=Host(`shop.development.claude`)"
    links:
      - claude_shop_php-fpm

  claude_shop_redis:
    extends:
      file: common.yml
      service: claude_shop_redis
    restart: always

networks:
  portal-net:
    external: true
  traefik-net:
    external: true
  database-net:
    external: true
